# 作業目標
在一個陣列中放入多屬性陣列，進一步對陣列做運算
作業重點
在建立結構化陣列前需要先設定屬性，在做運算時須注意資料屬性

題目:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]
呈上題，將array中體重(weight)數據集取出算出全部平均體重
呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重

In [1]:
import numpy as np 

In [14]:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

In [15]:
# 1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]

In [59]:
dt = np.dtype({'names':('name', 'sex', 'weight', 'rank', 'myopia'), 'formats':('U5', 'U5', np.float, np.int, np.bool)})

In [60]:
c = np.zeros(8, dtype = dt)

c['name'] = name_list
c['sex'] = sex_list
c['weight'] = weight_list
c['rank'] = rank_list
c['myopia'] = myopia_list

print(c)

[('小明', 'boy', 67.5, 8,  True) ('小華', 'boy', 75.3, 1,  True)
 ('小菁', 'girl', 50.1, 5, False) ('小美', 'girl', 45.5, 4, False)
 ('小張', 'boy', 80.8, 7,  True) ('John', 'boy', 90.4, 6,  True)
 ('Mark', 'boy', 78.4, 2, False) ('Tom', 'boy', 70.7, 3, False)]


In [61]:
# 2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重

In [62]:
print(np.mean(c['weight']))

69.8375


In [63]:
# 3. 呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重

In [69]:
print("Boy's Average: ")
print(np.mean(c[c['sex'] == 'boy']['weight']))
print("Girl's Average: ")
print(np.mean(c[c['sex'] == 'girl']['weight']))

Boy's Average: 
77.18333333333332
Girl's Average: 
47.8


# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [70]:
# np.zeros 將所有元素設為預設值，而 np.empty 沒有設數值，會比較快一點，可是之後需要另外設定值，否則元素將沒有任何值

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [2]:
# 記得先 Import 正確的套件



In [76]:
# 參考解答

a = np.random.rand(2, 3)

print(a)
print(np.round(a))

[[0.80982867 0.85207374 0.29423134]
 [0.10763425 0.61973026 0.39224327]]
[[1. 1. 0.]
 [0. 1. 0.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [78]:
m = 20
n = 40

print(np.round(n*a+m))

[[52. 54. 32.]
 [24. 45. 36.]]
