# [作業目標]

1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

# 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```


In [1]:
import numpy as np

a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 

In [2]:
print(a + a)
print(a + b)
print(a + c)
print(a + d)
print(a + e)

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


In [2]:
# 記得先 Import 正確的套件

import numpy as np


In [10]:
A = np.ones(3)*1
B = np.ones(3)*2

print(np.multiply(np.add(A,B),-1*A/2))

[-1.5 -1.5 -1.5]


In [9]:
result = np.zeros(3)

for i in np.arange(3):
    result[i] = (A[i]+B[i])*(-1*A[i]/2) 

print(result)

[-1.5 -1.5 -1.5]


### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


In [25]:
A = np.ones((1,6))
B = np.ones((6,1))

# Inner product
print(np.inner(A, np.transpose(B)))
print(A @ B)

[[6.]]
[[6.]]


In [26]:
# Outter product
print(np.outer(A, np.transpose(B)))
print(A * B)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


# 作業目標:
嘗試練習log的函式並應用
作業重點:
學員需要複習log的轉換方式
熟悉運用指數函數以及對數函數

題目:
運用投影片中的分貝公式回答下列問題。
1.正常的談話的聲壓為20000微巴斯卡，請問多少分貝?
2.30分貝的聲壓會是50分貝的幾倍?

In [3]:
np.log10(20000)

4.301029995663981

In [5]:
30**10/50**10

0.0060466176