# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [12]:
import numpy as np

a = np.arange(0,12).reshape(3,4)

print(a)

print(a.sum()) 
print(np.sum(a))
print(sum(a))

# sum(a) 同等於 a.sum(axis=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
66
[12 15 18 21]


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [13]:
# 記得先 Import 正確的套件

import numpy as np

In [16]:
A = np.random.random((5, 5))

print(A)

B = A/np.sqrt(A ** 2).sum()

print(B)
print(np.sqrt(B ** 2).sum())

# B is normalized A

[[0.73144249 0.6556332  0.01217835 0.40383016 0.39067983]
 [0.68893335 0.47073033 0.07896828 0.38260222 0.75160325]
 [0.25754903 0.46508703 0.53450798 0.3179539  0.34429237]
 [0.51352739 0.36666446 0.45320337 0.27261206 0.68775609]
 [0.87900522 0.68516401 0.06308159 0.62718167 0.71693561]]
[[0.06224447 0.05579324 0.00103636 0.03436524 0.03324617]
 [0.05862702 0.04005833 0.00672006 0.03255878 0.06396012]
 [0.02191697 0.03957809 0.04548569 0.02705732 0.02929868]
 [0.04370028 0.0312025  0.03856681 0.02319881 0.05852684]
 [0.0748018  0.05830626 0.00536813 0.05337206 0.06100996]]
0.9999999999999998


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [20]:
C = np.random.randint(100, size=10)

print(C)

C[C == C.max()] = -1

print(C)

[76 42 94 99 27 33 25 94 44 30]
[76 42 94 -1 27 33 25 94 44 30]
