In [2]:
import numpy as np

In [3]:
np.__version__

'1.19.2'

In [4]:
# 題目1: 生成一個等差數列，首數為 0，尾數為 20，公差為 1 的數列。

In [5]:
array1 = np.arange(0,21,1)

In [6]:
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [7]:
# 題目2: 呈上題，將以上數列取出偶數。

In [10]:
array2 = array1[::2]

In [11]:
print(array2)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [10]:
# 題目1: 呈 1 題，將數列取出 3 的倍數。

In [12]:
array3 = array1[3::3]

In [13]:
print(array3)

[ 3  6  9 12 15 18]
